### ISSUE TITLE
Handles only one client!!!

### ISSUE THREAD

**Issue by errogaht** [david-rahrer/nginx-opencart#1]
Hello!
Thankyou about this config - its work!
But probably - it can only handle one client:
if im run php script with call sleep(30);
and after run it -  im try to open opencart site - its not work.
when php code is executed - another php code cant be executed - why?

**Comment by errogaht** [comment]
it eacause in nginx config have lines about phpmyadmin! and im not use phpmyadmin
please comment it!
after im comment line about phpmyadmin - site works ok

**Comment by david-rahrer** [comment]
These configs are primarily for my own use though I understand others are using them. However, I have many sites running on the same server with no issues such as you describe. If you want to send me a test script to run the command(s) you say are causing OpenCart to stop, I will test it myself. I assume it is more than just sleep(30);

**Comment by errogaht** [comment]
Hello David, sorry about my panic, am try to switch opencart to apache - and same problem - this because when php_imap make connection to server whole PHP stun and no one can connect before IMAP server send responce :o:  
spleep(30) when running - site work normall, stun only when im try to estabilish imap connection )))
