### ISSUE TITLE
All except home and some

### ISSUE THREAD

**Issue by 3zzy** [david-rahrer/nginx-opencart#3]
First off, thanks for the effort.

SEO URLs work for products and categories but not for home where its still `index.php?route=common/home` and other pages including cart, checkout etc.

Is there anyway to make it work on all pages?

Thanks!

**Comment by david-rahrer** [comment]
I'm sorry, gmail treated this like a forum comment and it got lost. In case you haven't found a solution, here is a partial which takes care of the home page and could probably be adapted to take care of the other. I don't have time to take a look right now but you might. 

https://gist.github.com/david-rahrer/a8b78f3b4193a87f5606d9840af8fef1#file-remove_route-xml
